### ISSUE TITLE
Option to hide ZSH_VERSION?

### ISSUE THREAD

**Issue by willsoto** [molovo/filthy#2]
Love the work here! Thanks so much for it.

Would you be to open to an option to hide the `ZSH_VERSION` [here](https://github.com/molovo/filthy/blob/master/filthy.zsh#L155)?

**Comment by molovo** [comment]
Yes, I would. I've just pushed a new version which includes this. Thanks for the suggestion

**Comment by willsoto** [comment]
Thank you!
